Dev
Ade179/globe-walker pull request #3
Opened 2022-12-16 22:11 UTC by Ade179

Project has been completed 

- Followed Gitflow
- Project features are in the Readme.md file
-

2022-12-16 22:54 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @Ade179, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ All linters passing
✔️ Professional Readme
✔️ Good presentation
✔️ Correct Deployment of the App

## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 22:54 UTC, sja-thedude commented on src/Components/nav.css
> +
- [ ] Kindly make sure that your app design follows the design guidelines [here](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)).

2022-12-16 22:54 UTC, sja-thedude commented on src/test/Navigation.test.js
> +  const home = renderer.create(<Nav />);
- [ ] Kindly fix the error, currently one is failing.

<img width="513" alt="Screenshot 2022-12-17 at 1 47 11 AM" src="https://user-images.githubusercontent.com/70269507/208201783-2294713a-caae-4f24-9201-a08425902e32.png">

2022-12-17 07:00 UTC, mwanawabangona approved these changes
Hi @Ade179,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-17 07:01 UTC, merged